HOST = 0.0.0.0
PORT = 5000

export FLASK_APP=pyctogram
export FLASK_ENV=development
export APP_SETTINGS=pyctogram.config.DevelopmentConfig
export DATABASE_URL=sqlite:////$(PWD)/pyctogram/pycto.db
export MIGRATIONS=$(PWD)/migrations
export APP_LOG=pyctogram.log
export ALLOW_REGISTRATION=true
REQUIREMENTS = $(PWD)/requirements.txt

PYTHON_VERSION ?= python3.6
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask
PYTEST = $(VENV)/bin/py.test
