HOST = 0.0.0.0
PORT = 5000
APP_PATH = $(PWD)

export FLASK_APP=app.py
export FLASK_ENV=development

REQUIREMENTS = $(APP_PATH)/requirements.txt

PYTHON_VERSION ?= python3.6
VENV = $(PWD)/.venv
PYTHON = $(VENV)/bin/python
PIP = $(VENV)/bin/pip
FLASK = $(VENV)/bin/flask
PYTEST = $(VENV)/bin/py.test
